spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tblog?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
    username: root
    password: 986132
  application:
    name: tblog

server:
  servlet:
    context-path: /tblog
  port: 8088

mybatis-plus:
  configuration:
#    控制台输出生成的 SQL 语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

